project:
  type: website
  output-dir: docs

website:
  title: "EA078_Fall2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  live-html:
    theme: united
    css: styles.css
    toc: true



